In [42]:
import pandas as pd
import numpy as np

MAX_HOUR = 4.22

province_meta = pd.read_csv("data/province.csv", encoding= 'utf-8')
data = pd.read_csv("data/hour_matrix.csv", encoding = 'utf-8')
data.columns

Index(['Tỉnh', 'An Giang', 'Bến Tre', 'Bình Định', 'Bình Dương', 'Bình Thuận',
       'Cà Mau', 'Cần Thơ', 'Đà Nẵng', 'Đắk Lắk', 'Đồng Nai', 'Gia Lai',
       'Hà Giang', 'Hà Nội', 'Hồ Chí Minh', 'Khánh Hoà', 'Lai Châu', 'Long An',
       'Nghệ An', 'Ninh Bình', 'Quảng Bình', 'Quảng Ninh', 'Sơn La',
       'Tây Ninh', 'Thanh Hoá', 'Tuyên Quang'],
      dtype='object')

In [43]:
hour_matrix = province_meta[["ID","Tỉnh"]].join(data.set_index('Tỉnh'), on="Tỉnh")


In [44]:
tinh_id = hour_matrix[["ID","Tỉnh"]]
tinh_id = np.array(tinh_id).reshape((-1, 2))
tinh_id

array([[1, 'An Giang'],
       [2, 'Bến Tre'],
       [3, 'Bình Định'],
       [4, 'Bình Dương'],
       [5, 'Bình Thuận'],
       [6, 'Cà Mau'],
       [7, 'Cần Thơ'],
       [8, 'Đà Nẵng'],
       [9, 'Đắk Lắk'],
       [10, 'Đồng Nai'],
       [11, 'Gia Lai'],
       [12, 'Hà Giang'],
       [13, 'Hà Nội'],
       [14, 'Hồ Chí Minh'],
       [15, 'Khánh Hoà'],
       [16, 'Lai Châu'],
       [17, 'Long An'],
       [18, 'Nghệ An'],
       [19, 'Ninh Bình'],
       [20, 'Quảng Bình'],
       [21, 'Quảng Ninh'],
       [22, 'Sơn La'],
       [23, 'Tây Ninh'],
       [24, 'Thanh Hoá'],
       [25, 'Tuyên Quang']], dtype=object)

In [45]:
hour_matrix_ = hour_matrix.drop(columns= ['ID', 'Tỉnh'])
hour_matrix_ = np.array(hour_matrix_)
hour_matrix_

array([[ 0.     ,  2.86175, 13.9465 ,  3.88175,  7.4385 ,  4.056  ,
         1.3775 , 17.503  ,  9.53025,  4.083  , 12.175  , 34.5945 ,
        29.59425,  3.6245 , 11.49275, 33.7605 ,  2.71075, 23.03625,
        27.4705 , 19.785  , 29.6795 , 30.6855 ,  3.13825, 26.19475,
        31.7855 ],
       [ 2.86175,  0.     , 12.687  ,  2.7185 ,  5.07875,  4.8095 ,
         1.79625, 17.263  ,  8.36375,  2.54575, 11.5675 , 35.5675 ,
        30.3955 ,  1.98975,  9.59875, 35.03875,  1.206  , 23.89275,
        28.2415 , 20.45025, 30.17175, 31.9205 ,  3.4835 , 27.02   ,
        32.72525],
       [13.9465 , 12.687  ,  0.     , 10.22475,  8.46975, 17.417  ,
        13.96675,  6.941  ,  4.4185 , 10.21725,  3.35825, 27.552  ,
        22.0705 , 10.7825 ,  4.20625, 28.3645 , 11.78675, 16.5755 ,
        19.998  , 12.9935 , 20.7055 , 25.3005 , 10.90125, 19.132  ,
        24.76975],
       [ 3.88175,  2.7185 , 10.22475,  0.     ,  3.8885 ,  7.21475,
         3.743  , 14.5465 ,  5.8235 ,  0.4805 ,  8.87775, 3

In [46]:
tinh_id

array([[1, 'An Giang'],
       [2, 'Bến Tre'],
       [3, 'Bình Định'],
       [4, 'Bình Dương'],
       [5, 'Bình Thuận'],
       [6, 'Cà Mau'],
       [7, 'Cần Thơ'],
       [8, 'Đà Nẵng'],
       [9, 'Đắk Lắk'],
       [10, 'Đồng Nai'],
       [11, 'Gia Lai'],
       [12, 'Hà Giang'],
       [13, 'Hà Nội'],
       [14, 'Hồ Chí Minh'],
       [15, 'Khánh Hoà'],
       [16, 'Lai Châu'],
       [17, 'Long An'],
       [18, 'Nghệ An'],
       [19, 'Ninh Bình'],
       [20, 'Quảng Bình'],
       [21, 'Quảng Ninh'],
       [22, 'Sơn La'],
       [23, 'Tây Ninh'],
       [24, 'Thanh Hoá'],
       [25, 'Tuyên Quang']], dtype=object)

In [47]:
coverages = list()
for i,arr in enumerate(hour_matrix_):
    adapt = list()
    adapt_str = ""
    for j,hour in enumerate(arr):
        if MAX_HOUR > hour:
            adapt.append(tinh_id[j,0])
            
    for i, ad in enumerate(adapt):
        ad_str = str(ad) + ", "
        adapt_str = adapt_str + ad_str
    coverages.append(adapt_str[:-2])


coverages = [np.append(tid, coverages[i]) for i,tid in enumerate(tinh_id)]

coverages[:3]


[array([1, 'An Giang', '1, 2, 4, 6, 7, 10, 14, 17, 23'], dtype=object),
 array([2, 'Bến Tre', '1, 2, 4, 7, 10, 14, 17, 23'], dtype=object),
 array([3, 'Bình Định', '3, 11'], dtype=object)]

In [48]:
# Create dataframe
coverageDf = pd.DataFrame(coverages, columns= ["ID", "Tỉnh", "Coverage"])
coverageDf.to_csv("data/coverages.csv", index=False)